lang: ruby
env:
  - AS_VERSION=3.1.0
  - AS_VERSION=3.2.0
  - SINATRA_EDGE=true
install:
  - gem update --system
  - bundle update
rvm:
  - 1.8.7
  - 1.9.2
  - 1.9.3
  - ree
  - jruby
notifications:
  irc: 'irc.freenode.org#padrino'
  recipients:
    - nesquena@gmail.com
    - mr.arthur.chiu@gmail.com
    - joshbuddy@gmail.com
    - info@daddye.it
    - florian.gilcher@asquera.de
branches:
  only:
    - master
services: mongodb
allow_failures:
    - env: SINATRA_EDGE=true